/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacebarCounterRouteImport } from './routes/spacebar-counter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RightClickTestRouteImport } from './routes/right-click-test'
import { Route as ResultRouteImport } from './routes/result'
import { Route as IndexRouteImport } from './routes/index'

const SpacebarCounterRoute = SpacebarCounterRouteImport.update({
  id: '/spacebar-counter',
  path: '/spacebar-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RightClickTestRoute = RightClickTestRouteImport.update({
  id: '/right-click-test',
  path: '/right-click-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/right-click-test': typeof RightClickTestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spacebar-counter': typeof SpacebarCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/right-click-test': typeof RightClickTestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spacebar-counter': typeof SpacebarCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/right-click-test': typeof RightClickTestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spacebar-counter': typeof SpacebarCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/result'
    | '/right-click-test'
    | '/sitemap.xml'
    | '/spacebar-counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/result'
    | '/right-click-test'
    | '/sitemap.xml'
    | '/spacebar-counter'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/right-click-test'
    | '/sitemap.xml'
    | '/spacebar-counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  RightClickTestRoute: typeof RightClickTestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpacebarCounterRoute: typeof SpacebarCounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spacebar-counter': {
      id: '/spacebar-counter'
      path: '/spacebar-counter'
      fullPath: '/spacebar-counter'
      preLoaderRoute: typeof SpacebarCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/right-click-test': {
      id: '/right-click-test'
      path: '/right-click-test'
      fullPath: '/right-click-test'
      preLoaderRoute: typeof RightClickTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  RightClickTestRoute: RightClickTestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpacebarCounterRoute: SpacebarCounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
